import React, { createContext, useState, useContext } from 'react';

const translations = {
  ko: {
    siteName: "Arcana Insight",
    heroTitle: "전 세계 타로 데이터 기반의 정확한 운세 안내",
    heroDesc: "수백 년간 축적된 전 세계의 방대한 타로 데이터와 해석학을 바탕으로, 당신의 현재 상황을 정확하게 꿰뚫어보고 나아갈 길을 안내합니다. AI의 빠름과 전통 타로의 깊이를 결합한 최상의 인사이트를 경험하세요.",
    whyTitle: "왜 아르카나 인사이트인가?",
    feature1Title: "글로벌 데이터베이스",
    feature1Desc: "동서양을 아우르는 수만 건의 타로 리딩 데이터를 기반으로 가장 객관적이고 정확한 해석을 제공합니다.",
    feature2Title: "심층적인 통찰력",
    feature2Desc: "단순한 운세가 아닌, 심리학과 상징학이 결합된 깊이 있는 조언으로 당신의 고민을 실질적으로 해결합니다.",
    feature3Title: "개인 맞춤형 리딩",
    feature3Desc: "당신의 고유한 상황과 질문의 흐름을 분석하여 지금 당장 가장 알맞은 타로 해답을 제시합니다.",
    startSectionTitle: "지금 바로 당신의 운명을 확인하세요",
    freeReadTitle: "오늘의 인사이트 (무료)",
    freeReadDesc: "가볍게 1장을 뽑아 현재 당신에게 가장 필요한 팩폭 조언을 확인하세요.",
    freeReadBtn: "1장 무료 뽑기",
    basicReadTitle: "베이직 리딩 (3장)",
    basicReadDesc: "과거, 현재, 미래의 흐름을 파악하여 당면한 문제의 원인과 결과를 분석합니다.",
    basicReadBtn: "3장 심층 상담 ($2.99)",
    premiumReadTitle: "프리미엄 리딩 (5장)",
    premiumReadDesc: "주변 상황, 숨겨진 의미, 구체적인 행동 지침까지 종합적인 해결책을 제시합니다.",
    premiumReadBtn: "5장 정밀 분석 ($4.99)",
    vipReadTitle: "VIP 켈틱 크로스 (10장)",
    vipReadDesc: "타로 최고 권위의 10장 배열법으로 당신의 무의식부터 최종 결과까지 완벽히 해부합니다.",
    vipReadBtn: "10장 궁극의 상담 ($8.99)",
    footerText: "© 2026 Arcana Insight. All rights reserved."
  },
  en: {
    siteName: "Arcana Insight",
    heroTitle: "Accurate Guidance Based on Global Tarot Data",
    heroDesc: "Based on vast tarot data and hermeneutics accumulated over centuries worldwide, we accurately see through your current situation and guide your path. Experience the best insight combining the speed of AI with the depth of traditional tarot.",
    whyTitle: "Why Arcana Insight?",
    feature1Title: "Global Database",
    feature1Desc: "Provides the most objective and accurate interpretation based on tens of thousands of tarot reading data spanning East and West.",
    feature2Title: "Deep Insight",
    feature2Desc: "Practically resolves your concerns with in-depth advice combining psychology and symbology, not just simple fortunes.",
    feature3Title: "Personalized Reading",
    feature3Desc: "Analyzes the unique flow of your situation and questions to present the most appropriate tarot answers right now.",
    startSectionTitle: "Check Your Destiny Right Now",
    freeReadTitle: "Today's Insight (Free)",
    freeReadDesc: "Lightly draw 1 card to check the blunt advice you need most right now.",
    freeReadBtn: "Start 1 Free Reading",
    basicReadTitle: "Basic Reading (3 Cards)",
    basicReadDesc: "Analyze the cause and effect of your current problems by understanding the flow of past, present, and future.",
    basicReadBtn: "Deep Consultation ($2.99)",
    premiumReadTitle: "Premium Reading (5 Cards)",
    premiumReadDesc: "Provides comprehensive solutions including surroundings, hidden meanings, and specific action guidelines.",
    premiumReadBtn: "Precision Analysis ($4.99)",
    vipReadTitle: "VIP Celtic Cross (10 Cards)",
    vipReadDesc: "The ultimate 10-card spread completely dissects everything from your subconscious to the final outcome.",
    vipReadBtn: "Ultimate Consultation ($8.99)",
    footerText: "© 2026 Arcana Insight. All rights reserved."
  },
  ja: {
    siteName: "Arcana Insight",
    heroTitle: "世界中のタロットデータに基づく正確な運勢案内",
    heroDesc: "何百年にもわたって蓄積された世界中の膨大なタロットデータと解釈学に基づき、あなたの現状を正確に見抜き、進むべき道を案内します。AIの速さと伝統的なタロットの深みを組み合わせた最高の洞察を体験してください。",
    whyTitle: "なぜ Arcana Insight なのか？",
    feature1Title: "グローバルデータベース",
    feature1Desc: "洋の東西を問わず数万件のタロットリーディングデータを学習し、最も客観的で正確な解釈を提供します。",
    feature2Title: "深い洞察力",
    feature2Desc: "単なる運勢ではなく、心理学と象徴学が結びついた深みのあるアドバイスで、あなたの悩みを実質的に解決します。",
    feature3Title: "パーソナライズされたリーディング",
    feature3Desc: "あなたの固有の状況と質問の流れを分析し、今最も適切なタロットの答えを提示します。",
    startSectionTitle: "今すぐあなたの運命を確認する",
    freeReadTitle: "今日のインサイト（無料）",
    freeReadDesc: "軽く1枚を引いて、今あなたに最も必要な核心となるメッセージを確認してください。",
    freeReadBtn: "1枚無料リーディング",
    basicReadTitle: "ベーシックリーディング（3枚）",
    basicReadDesc: "過去、現在、未来の流れを把握し、直面している問題の原因と結果を分析します。",
    basicReadBtn: "深層相談 ($2.99)",
    premiumReadTitle: "プレミアムリーディング（5枚）",
    premiumReadDesc: "周囲の状況、隠された意味、具体的な行動指針まで、総合的な解決策を提示します。",
    premiumReadBtn: "精密分析 ($4.99)",
    vipReadTitle: "VIP ケルティック・クロス（10枚）",
    vipReadDesc: "タロット最高権威の10枚スプレッドで、あなたの無意識から最終結果まで完全に解剖します。",
    vipReadBtn: "究極の相談 ($8.99)",
    footerText: "© 2026 Arcana Insight. All rights reserved."
  },
  zh: {
    siteName: "Arcana Insight",
    heroTitle: "基于全球塔罗数据的准确运势指南",
    heroDesc: "基于数百年来全球积累的海量塔罗数据和解释学，准确看透您的现状并指引您前进的道路。体验结合AI速度与传统塔罗深度的最佳洞察力。",
    whyTitle: "为什么选择 Arcana Insight？",
    feature1Title: "全球数据库",
    feature1Desc: "基于东西方数万条塔罗占卜数据，提供最客观、最准确的解读。",
    feature2Title: "深度洞察",
    feature2Desc: "不仅仅是简单的运势，而是结合心理学和符号学的深度建议，实质性地解决您的烦恼。",
    feature3Title: "个性化解读",
    feature3Desc: "分析您独特的状况和问题走向，为您提供当下最合适的塔罗解答。",
    startSectionTitle: "立即确认您的命运",
    freeReadTitle: "今日洞察 (免费)",
    freeReadDesc: "轻松抽取1张牌，确认您目前最需要的直言不讳的建议。",
    freeReadBtn: "开始1张免费占卜",
    basicReadTitle: "基础占卜 (3张)",
    basicReadDesc: "通过把握过去、现在和未来的趋势，分析当前问题的原因和结果。",
    basicReadBtn: "深度咨询 ($2.99)",
    premiumReadTitle: "高级占卜 (5张)",
    premiumReadDesc: "提供包括周围环境、隐藏含义和具体行动指南在内的综合解决方案。",
    premiumReadBtn: "精密分析 ($4.99)",
    vipReadTitle: "VIP 凯尔特十字 (10张)",
    vipReadDesc: "塔罗界最高权威的10张牌阵，从您的潜意识彻底解剖到最终结果。",
    vipReadBtn: "终极咨询 ($8.99)",
    footerText: "© 2026 Arcana Insight. All rights reserved."
  },
  es: {
    siteName: "Arcana Insight",
    heroTitle: "Orientación precisa basada en datos globales de Tarot",
    heroDesc: "Basado en vastos datos de tarot y hermenéutica acumulados a lo largo de siglos en todo el mundo, vemos con precisión su situación actual y guiamos su camino. Experimente la mejor perspectiva combinando la velocidad de la IA con la profundidad del tarot tradicional.",
    whyTitle: "¿Por qué Arcana Insight?",
    feature1Title: "Base de datos global",
    feature1Desc: "Proporciona la interpretación más objetiva y precisa basada en decenas de miles de datos de lectura de tarot de Oriente y Occidente.",
    feature2Title: "Percepción profunda",
    feature2Desc: "Resuelve sus preocupaciones con consejos detallados que combinan psicología y simbología, no solo predicciones simples.",
    feature3Title: "Lectura personalizada",
    feature3Desc: "Analiza el flujo único de su situación y preguntas para presentar las respuestas de tarot más apropiadas en este momento.",
    startSectionTitle: "Compruebe su destino ahora mismo",
    freeReadTitle: "Perspectiva de hoy (Gratis)",
    freeReadDesc: "Saque ligeramente 1 carta para comprobar el consejo directo que más necesita en este momento.",
    freeReadBtn: "Iniciar 1 lectura gratis",
    basicReadTitle: "Lectura Básica (3 Cartas)",
    basicReadDesc: "Analice la causa y el efecto de sus problemas actuales comprendiendo el flujo del pasado, presente y futuro.",
    basicReadBtn: "Consulta Profunda ($2.99)",
    premiumReadTitle: "Lectura Premium (5 Cartas)",
    premiumReadDesc: "Proporciona soluciones integrales que incluyen el entorno, significados ocultos y pautas de acción específicas.",
    premiumReadBtn: "Análisis de Precisión ($4.99)",
    vipReadTitle: "VIP Cruz Celta (10 Cartas)",
    vipReadDesc: "La tirada de 10 cartas definitiva disecciona completamente todo, desde tu subconsciente hasta el resultado final.",
    vipReadBtn: "Consulta Definitiva ($8.99)",
    footerText: "© 2026 Arcana Insight. Todos los derechos reservados."
  },
  fr: {
    siteName: "Arcana Insight",
    heroTitle: "Orientation précise basée sur des données mondiales de Tarot",
    heroDesc: "En nous basant sur de vastes données de tarot et d'herméneutique accumulées au fil des siècles dans le monde entier, nous voyons avec précision votre situation actuelle et guidons votre chemin. Découvrez la meilleure perspective en combinant la vitesse de l'IA avec la profondeur du tarot traditionnel.",
    whyTitle: "Pourquoi Arcana Insight ?",
    feature1Title: "Base de données mondiale",
    feature1Desc: "Fournit l'interprétation la plus objective et précise basée sur des dizaines de milliers de données de lecture de tarot d'Orient et d'Occident.",
    feature2Title: "Aperçu profond",
    feature2Desc: "Résout vos préoccupations avec des conseils approfondis combinant psychologie et symbologie, pas seulement de simples prédictions.",
    feature3Title: "Lecture personnalisée",
    feature3Desc: "Analyse le flux unique de votre situation et de vos questions pour présenter les réponses de tarot les plus appropriées en ce moment.",
    startSectionTitle: "Vérifiez votre destin dès maintenant",
    freeReadTitle: "Aperçu d'aujourd'hui (Gratuit)",
    freeReadDesc: "Tirez légèrement 1 carte pour vérifier le conseil direct dont vous avez le plus besoin en ce moment.",
    freeReadBtn: "Commencer 1 lecture",
    basicReadTitle: "Lecture Basique (3 Cartes)",
    basicReadDesc: "Analysez la cause et l'effet de vos problèmes actuels en comprenant le flux du passé, du présent et du futur.",
    basicReadBtn: "Consultation Profonde (2,99 $)",
    premiumReadTitle: "Lecture Premium (5 Cartas)",
    premiumReadDesc: "Fournit des solutions complètes incluant l'environnement, les significations cachées et des directives d'action spécifiques.",
    premiumReadBtn: "Analyse de Précision (4,99 $)",
    vipReadTitle: "VIP Croix Celtique (10 Cartes)",
    vipReadDesc: "Le tirage ultime de 10 cartes dissèque complètement tout, de votre subconscient au résultat final.",
    vipReadBtn: "Consultation Ultime (8,99 $)",
    footerText: "© 2026 Arcana Insight. Tous droits réservés."
  },
  th: {
    siteName: "Arcana Insight",
    heroTitle: "คำแนะนำดวงชะตาที่แม่นยำ อิงจากข้อมูลไพ่ทาโรต์ทั่วโลก",
    heroDesc: "จากข้อมูลไพ่ทาโรต์และวิชาตีความที่สะสมมาหลายศตวรรษทั่วโลก เรามองเห็นสถานการณ์ปัจจุบันของคุณอย่างแม่นยำและนำทางคุณ สัมผัสวิสัยทัศน์ที่ดีที่สุดที่ผสมผสานความเร็วของ AI และความลึกซึ้งของไพ่ทาโรต์ดั้งเดิม",
    whyTitle: "ทำไมต้อง Arcana Insight?",
    feature1Title: "ฐานข้อมูลระดับโลก",
    feature1Desc: "ให้การตีความที่เที่ยงตรงและแม่นยำที่สุด โดยอิงจากข้อมูลการอ่านไพ่ทาโรต์นับหมื่นรายการจากทั้งตะวันออกและตะวันตก",
    feature2Title: "ข้อมูลเชิงลึกที่ล้ำลึก",
    feature2Desc: "แก้ไขข้อกังวลของคุณด้วยคำแนะนำที่ลึกซึ้งซึ่งผสมผสานจิตวิทยาและสัญลักษณ์วิทยา ไม่ใช่แค่คำทำนายทั่วไป",
    feature3Title: "การอ่านแบบส่วนตัว",
    feature3Desc: "วิเคราะห์กระแสสถานการณ์และคำถามที่ไม่เหมือนใครของคุณ เพื่อนำเสนอคำตอบของไพ่ทาโรต์ที่เหมาะสมที่สุดในขณะนี้",
    startSectionTitle: "ตรวจสอบโชคชะตาของคุณตอนนี้",
    freeReadTitle: "ข้อมูลเชิงลึกวันนี้ (ฟรี)",
    freeReadDesc: "จั่วไพ่ 1 ใบเบาๆ เพื่อรับคำแนะนำตรงไปตรงมาที่คุณต้องการมากที่สุด",
    freeReadBtn: "เริ่มอ่านฟรี 1 ใบ",
    basicReadTitle: "การอ่านพื้นฐาน (ไพ่ 3 ใบ)",
    basicReadDesc: "วิเคราะห์สาเหตุและผลลัพธ์ของปัญหาปัจจุบันของคุณโดยทำความเข้าใจกระแสอดีต ปัจจุบัน และอนาคต",
    basicReadBtn: "ปรึกษาเชิงลึก ($2.99)",
    premiumReadTitle: "การอ่านระดับพรีเมียม (ไพ่ 5 ใบ)",
    premiumReadDesc: "ให้การแก้ปัญหาแบบครอบคลุม รวมถึงสภาพแวดล้อม ความหมายที่ซ่อนอยู่ และแนวทางการดำเนินการที่ชัดเจน",
    premiumReadBtn: "วิเคราะห์แม่นยำ ($4.99)",
    vipReadTitle: "VIP เซลติกครอส (ไพ่ 10 ใบ)",
    vipReadDesc: "การจัดไพ่ 10 ใบขั้นสูงสุดที่เจาะลึกทุกอย่างตั้งแต่จิตใต้สำนึกของคุณไปจนถึงผลลัพธ์สุดท้าย",
    vipReadBtn: "การปรึกษาขั้นสุดยอด ($8.99)",
    footerText: "© 2026 Arcana Insight. สงวนลิขสิทธิ์."
  },
  vi: {
    siteName: "Arcana Insight",
    heroTitle: "Hướng Dẫn Vận Mệnh Chính Xác Dựa Trên Dữ Liệu Tarot Toàn Cầu",
    heroDesc: "Dựa trên dữ liệu tarot khổng lồ và thuật diễn giải được tích lũy qua nhiều thế kỷ trên toàn thế giới, chúng tôi nhìn thấu chính xác tình hình hiện tại và dẫn đường cho bạn. Trải nghiệm sự thấu hiểu tuyệt vời nhất kết hợp giữa tốc độ của AI và chiều sâu của tarot truyền thống.",
    whyTitle: "Tại sao chọn Arcana Insight?",
    feature1Title: "Cơ Sở Dữ Liệu Toàn Cầu",
    feature1Desc: "Cung cấp sự diễn giải khách quan và chính xác nhất dựa trên hàng chục nghìn dữ liệu đọc tarot từ cả phương Đông và phương Tây.",
    feature2Title: "Sự Thấu Hiểu Sâu Sắc",
    feature2Desc: "Giải quyết những trăn trở của bạn bằng lời khuyên sâu sắc kết hợp giữa tâm lý học và biểu tượng học, không chỉ là bói toán đơn thuần.",
    feature3Title: "Đọc Bài Cá Nhân Hóa",
    feature3Desc: "Phân tích dòng chảy tình huống và câu hỏi độc đáo của bạn để đưa ra câu trả lời tarot phù hợp nhất ngay lúc này.",
    startSectionTitle: "Kiểm Tra Vận Mệnh Của Bạn Ngay Bây Giờ",
    freeReadTitle: "Thông Điệp Hôm Nay (Miễn Phí)",
    freeReadDesc: "Nhẹ nhàng rút 1 lá bài để xem lời khuyên thẳng thắn mà bạn cần nhất lúc này.",
    freeReadBtn: "Bắt Đầu Rút 1 Lá",
    basicReadTitle: "Đọc Cơ Bản (3 Lá)",
    basicReadDesc: "Phân tích nguyên nhân và kết quả của các vấn đề hiện tại bằng cách hiểu dòng chảy của quá khứ, hiện tại và tương lai.",
    basicReadBtn: "Tư Vấn Chuyên Sâu ($2.99)",
    premiumReadTitle: "Đọc Cao Cấp (5 Lá)",
    premiumReadDesc: "Cung cấp các giải pháp toàn diện bao gồm môi trường xung quanh, ý nghĩa ẩn giấu và các hướng dẫn hành động cụ thể.",
    premiumReadBtn: "Phân Tích Chính Xác ($4.99)",
    vipReadTitle: "VIP Trải Bài Celtic Cross (10 Lá)",
    vipReadDesc: "Trải bài 10 lá tối thượng phân tích hoàn toàn mọi thứ từ tiềm thức của bạn cho đến kết quả cuối cùng.",
    vipReadBtn: "Tư Vấn Tối Thượng ($8.99)",
    footerText: "© 2026 Arcana Insight. Đã đăng ký bản quyền."
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('ko');
  const t = (key) => translations[lang][key] || key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
