export const tarotDeck = [
  // Major Arcana (22)
  { id: 0, name: "The Fool", nameKo: "바보", image: "/tarot-cards/0.jpg" },
  { id: 1, name: "The Magician", nameKo: "마법사", image: "/tarot-cards/1.jpg" },
  { id: 2, name: "The High Priestess", nameKo: "고위 여사제", image: "/tarot-cards/2.jpg" },
  { id: 3, name: "The Empress", nameKo: "여황제", image: "/tarot-cards/3.jpg" },
  { id: 4, name: "The Emperor", nameKo: "황제", image: "/tarot-cards/4.jpg" },
  { id: 5, name: "The Hierophant", nameKo: "교황", image: "/tarot-cards/5.jpg" },
  { id: 6, name: "The Lovers", nameKo: "연인", image: "/tarot-cards/6.jpg" },
  { id: 7, name: "The Chariot", nameKo: "전차", image: "/tarot-cards/7.jpg" },
  { id: 8, name: "Strength", nameKo: "힘", image: "/tarot-cards/8.jpg" },
  { id: 9, name: "The Hermit", nameKo: "은둔자", image: "/tarot-cards/9.jpg" },
  { id: 10, name: "Wheel of Fortune", nameKo: "운명의 수레바퀴", image: "/tarot-cards/10.jpg" },
  { id: 11, name: "Justice", nameKo: "정의", image: "/tarot-cards/11.jpg" },
  { id: 12, name: "The Hanged Man", nameKo: "매달린 사람", image: "/tarot-cards/12.jpg" },
  { id: 13, name: "Death", nameKo: "죽음", image: "/tarot-cards/13.jpg" },
  { id: 14, name: "Temperance", nameKo: "절제", image: "/tarot-cards/14.jpg" },
  { id: 15, name: "The Devil", nameKo: "악마", image: "/tarot-cards/15.jpg" },
  { id: 16, name: "The Tower", nameKo: "탑", image: "/tarot-cards/16.jpg" },
  { id: 17, name: "The Star", nameKo: "별", image: "/tarot-cards/17.jpg" },
  { id: 18, name: "The Moon", nameKo: "달", image: "/tarot-cards/18.jpg" },
  { id: 19, name: "The Sun", nameKo: "태양", image: "/tarot-cards/19.jpg" },
  { id: 20, name: "Judgement", nameKo: "심판", image: "/tarot-cards/20.jpg" },
  { id: 21, name: "The World", nameKo: "세계", image: "/tarot-cards/21.jpg" },

  // Minor Arcana - Wands (14)
  { id: 22, name: "Ace of Wands", nameKo: "지팡이 에이스", image: "/tarot-cards/22.jpg" },
  { id: 23, name: "Two of Wands", nameKo: "지팡이 2", image: "/tarot-cards/23.jpg" },
  { id: 24, name: "Three of Wands", nameKo: "지팡이 3", image: "/tarot-cards/24.jpg" },
  { id: 25, name: "Four of Wands", nameKo: "지팡이 4", image: "/tarot-cards/25.jpg" },
  { id: 26, name: "Five of Wands", nameKo: "지팡이 5", image: "/tarot-cards/26.jpg" },
  { id: 27, name: "Six of Wands", nameKo: "지팡이 6", image: "/tarot-cards/27.jpg" },
  { id: 28, name: "Seven of Wands", nameKo: "지팡이 7", image: "/tarot-cards/28.jpg" },
  { id: 29, name: "Eight of Wands", nameKo: "지팡이 8", image: "/tarot-cards/29.jpg" },
  { id: 30, name: "Nine of Wands", nameKo: "지팡이 9", image: "/tarot-cards/30.jpg" },
  { id: 31, name: "Ten of Wands", nameKo: "지팡이 10", image: "/tarot-cards/31.jpg" },
  { id: 32, name: "Page of Wands", nameKo: "지팡이 시종", image: "/tarot-cards/32.jpg" },
  { id: 33, name: "Knight of Wands", nameKo: "지팡이 기사", image: "/tarot-cards/33.jpg" },
  { id: 34, name: "Queen of Wands", nameKo: "지팡이 여왕", image: "/tarot-cards/34.jpg" },
  { id: 35, name: "King of Wands", nameKo: "지팡이 왕", image: "/tarot-cards/35.jpg" },

  // Minor Arcana - Cups (14)
  { id: 36, name: "Ace of Cups", nameKo: "컵 에이스", image: "/tarot-cards/36.jpg" },
  { id: 37, name: "Two of Cups", nameKo: "컵 2", image: "/tarot-cards/37.jpg" },
  { id: 38, name: "Three of Cups", nameKo: "컵 3", image: "/tarot-cards/38.jpg" },
  { id: 39, name: "Four of Cups", nameKo: "컵 4", image: "/tarot-cards/39.jpg" },
  { id: 40, name: "Five of Cups", nameKo: "컵 5", image: "/tarot-cards/40.jpg" },
  { id: 41, name: "Six of Cups", nameKo: "컵 6", image: "/tarot-cards/41.jpg" },
  { id: 42, name: "Seven of Cups", nameKo: "컵 7", image: "/tarot-cards/42.jpg" },
  { id: 43, name: "Eight of Cups", nameKo: "컵 8", image: "/tarot-cards/43.jpg" },
  { id: 44, name: "Nine of Cups", nameKo: "컵 9", image: "/tarot-cards/44.jpg" },
  { id: 45, name: "Ten of Cups", nameKo: "컵 10", image: "/tarot-cards/45.jpg" },
  { id: 46, name: "Page of Cups", nameKo: "컵 시종", image: "/tarot-cards/46.jpg" },
  { id: 47, name: "Knight of Cups", nameKo: "컵 기사", image: "/tarot-cards/47.jpg" },
  { id: 48, name: "Queen of Cups", nameKo: "컵 여왕", image: "/tarot-cards/48.jpg" },
  { id: 49, name: "King of Cups", nameKo: "컵 왕", image: "/tarot-cards/49.jpg" },

  // Minor Arcana - Swords (14)
  { id: 50, name: "Ace of Swords", nameKo: "검 에이스", image: "/tarot-cards/50.jpg" },
  { id: 51, name: "Two of Swords", nameKo: "검 2", image: "/tarot-cards/51.jpg" },
  { id: 52, name: "Three of Swords", nameKo: "검 3", image: "/tarot-cards/52.jpg" },
  { id: 53, name: "Four of Swords", nameKo: "검 4", image: "/tarot-cards/53.jpg" },
  { id: 54, name: "Five of Swords", nameKo: "검 5", image: "/tarot-cards/54.jpg" },
  { id: 55, name: "Six of Swords", nameKo: "검 6", image: "/tarot-cards/55.jpg" },
  { id: 56, name: "Seven of Swords", nameKo: "검 7", image: "/tarot-cards/56.jpg" },
  { id: 57, name: "Eight of Swords", nameKo: "검 8", image: "/tarot-cards/57.jpg" },
  { id: 58, name: "Nine of Swords", nameKo: "검 9", image: "/tarot-cards/58.jpg" },
  { id: 59, name: "Ten of Swords", nameKo: "검 10", image: "/tarot-cards/59.jpg" },
  { id: 60, name: "Page of Swords", nameKo: "검 시종", image: "/tarot-cards/60.jpg" },
  { id: 61, name: "Knight of Swords", nameKo: "검 기사", image: "/tarot-cards/61.jpg" },
  { id: 62, name: "Queen of Swords", nameKo: "검 여왕", image: "/tarot-cards/62.jpg" },
  { id: 63, name: "King of Swords", nameKo: "검 왕", image: "/tarot-cards/63.jpg" },

  // Minor Arcana - Pentacles (14)
  { id: 64, name: "Ace of Pentacles", nameKo: "펜타클 에이스", image: "/tarot-cards/64.jpg" },
  { id: 65, name: "Two of Pentacles", nameKo: "펜타클 2", image: "/tarot-cards/65.jpg" },
  { id: 66, name: "Three of Pentacles", nameKo: "펜타클 3", image: "/tarot-cards/66.jpg" },
  { id: 67, name: "Four of Pentacles", nameKo: "펜타클 4", image: "/tarot-cards/67.jpg" },
  { id: 68, name: "Five of Pentacles", nameKo: "펜타클 5", image: "/tarot-cards/68.jpg" },
  { id: 69, name: "Six of Pentacles", nameKo: "펜타클 6", image: "/tarot-cards/69.jpg" },
  { id: 70, name: "Seven of Pentacles", nameKo: "펜타클 7", image: "/tarot-cards/70.jpg" },
  { id: 71, name: "Eight of Pentacles", nameKo: "펜타클 8", image: "/tarot-cards/71.jpg" },
  { id: 72, name: "Nine of Pentacles", nameKo: "펜타클 9", image: "/tarot-cards/72.jpg" },
  { id: 73, name: "Ten of Pentacles", nameKo: "펜타클 10", image: "/tarot-cards/73.jpg" },
  { id: 74, name: "Page of Pentacles", nameKo: "펜타클 시종", image: "/tarot-cards/74.jpg" },
  { id: 75, name: "Knight of Pentacles", nameKo: "펜타클 기사", image: "/tarot-cards/75.jpg" },
  { id: 76, name: "Queen of Pentacles", nameKo: "펜타클 여왕", image: "/tarot-cards/76.jpg" },
  { id: 77, name: "King of Pentacles", nameKo: "펜타클 왕", image: "/tarot-cards/77.jpg" },
];
